spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DEV_DB:fincore_dev}
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev-migration

fincore:
  demo:
    seed:
      enabled: ${FINCORE_DEMO_SEED_ENABLED:false}
