package io.github.alejandro117b.fincore.transfer;

public enum TransferErrorCode {
    INVALID_REQUEST, INVALID_AMOUNT, INVALID_CURRENCY, SAME_ACCOUNT,
    ACCOUNT_NOT_FOUND, ACCOUNT_BLOCKED, ACCOUNT_CLOSED, CURRENCY_MISMATCH,
    LEDGER_ACCOUNT_NOT_FOUND, INSUFFICIENT_FUNDS, IDEMPOTENCY_CONFLICT
}
